# name: Build and Deploy API

# on:
#   workflow_dispatch:
#   # push:
#   #   branches:
#   #     - main

# env:
#   AZURE_PYTHON_WEBAPP_NAME_REST: prod-api-app-api-python-sruinard    
#   AZURE_PYTHON_WEBAPP_ROOT: '.'
#   AZURE_PYTHON_WEBAPP_PACKAGE_PATH_REST: './dist/'
# jobs:
#   build:
#     defaults:
#       run:
#         working-directory: ${{ env.AZURE_PYTHON_WEBAPP_ROOT }}
#     name: Build and Deploy PYTHON REST API
#     environment: production
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
    
#     - uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}

#     - name: Set up Python 3.x
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.x
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install wheel
#         python setup.py bdist_wheel 
#     - uses: actions/upload-artifact@v2
#       with:
#         name: webshop
#         path: ${{ env.AZURE_PYTHON_WEBAPP_PACKAGE_PATH_REST }}
  
#   # DEPLOY TO DEVELOPMENT
#   deploy_dev:
#     name: Deploy to Dev Environment
#     needs: [build] 
#     runs-on: ubuntu-latest
#     environment:
#       name: development
#     steps:
#     - uses: actions/checkout@v2
    
#     - uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}

#     - uses: actions/download-artifact@v2
#       with:
#         name: webshop
#     - name: Set up Python 3.x
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.x
#     - name: Deploy web App using GH Action azure/webapps-deploy
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: dev-api-app-api-python-sruinard
#         package: ${{ env.AZURE_PYTHON_WEBAPP_ROOT }}
#         startup-command: "pip install *.whl && python -m uvicorn webshop.app:app --host 0.0.0.0"

  # # DEPLOY TO PROD
  # deploy_prod:
  #   name: Deploy to Production Environment
  #   needs: [build, deploy_dev] 
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: production
  #   steps:
  #   - uses: actions/checkout@v2
    
  #   - uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}

  #   - uses: actions/download-artifact@v2
  #     with:
  #       name: webshop
  #   - name: Set up Python 3.x
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.x
  #   - name: Deploy web App using GH Action azure/webapps-deploy
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: prod-api-app-api-python-sruinard
  #       package: ${{ env.AZURE_PYTHON_WEBAPP_ROOT }}
  #       startup-command: "pip install *.whl && python -m uvicorn webshop.app:app --host 0.0.0.0"


name: Build and Deploy Distributed Tracing

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  AZURE_PYTHON_WEBAPP_WEBSHOP: srtrace-webshop  
  AZURE_PYTHON_WEBAPP_PAYMENTS: srtrace-payments
  AZURE_PYTHON_WEBAPP_SHIPPING: srtrace-shipping 

  WEBSHOP_ROOT: './apps/webshop'
  PAYMENTS_ROOT: './apps/payments'
  SHIPPING_ROOT: './apps/shipping'

  WEBSHOP_PACKAGE: './apps/webshop/dist/'
  PAYMENTS_PACKAGE: './apps/payments/dist/'
  SHIPPING_PACKAGE: './apps/shipping/dist/'
jobs:
  
  build_webshop:
    defaults:
      run:
        working-directory: ${{ env.WEBSHOP_ROOT }}
    name: build_and_deploy webshop
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        python setup.py bdist_wheel 
    - uses: actions/upload-artifact@v2
      with:
        name: webshop
        path: ${{ env.WEBSHOP_PACKAGE }}
  
  deploy_webshop:
    name: Deploy webshop
    needs: [build_webshop] 
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: actions/download-artifact@v2
      with:
        name: webshop
        path: ${{ env.WEBSHOP_ROOT }}
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_PYTHON_WEBAPP_WEBSHOP }}
        package:  ${{ env.WEBSHOP_ROOT }}
        startup-command: "pip install *.whl && python -m uvicorn webshop.app:app --host 0.0.0.0"

  build_payments:
    defaults:
      run:
        working-directory: ${{ env.PAYMENTS_ROOT }}
    name: build_and_deploy payments
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        python setup.py bdist_wheel 
    - uses: actions/upload-artifact@v2
      with:
        name: payments
        path: ${{ env.PAYMENTS_PACKAGE }}
  
  deploy_payments:
    name: Deploy payments
    needs: [build_payments] 
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: actions/download-artifact@v2
      with:
        name: payments
        path: ${{ env.PAYMENTS_ROOT }}
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_PYTHON_WEBAPP_PAYMENTS }}
        package: ${{ env.PAYMENTS_ROOT }}
        startup-command: "pip install *.whl && python -m uvicorn payments.app:app --host 0.0.0.0"

  build_shipping:
    defaults:
      run:
        working-directory: ${{ env.SHIPPING_ROOT }}
    name: build_and_deploy shipping
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        python setup.py bdist_wheel 
    - uses: actions/upload-artifact@v2
      with:
        name: shipping
        path: ${{ env.SHIPPING_PACKAGE }}
  
  deploy_shipping:
    name: Deploy shipping
    needs: [build_shipping] 
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: actions/download-artifact@v2
      with:
        name: shipping
        path: ${{ env.SHIPPING_ROOT }}
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_PYTHON_WEBAPP_SHIPPING }}
        package: ${{ env.SHIPPING_ROOT }}
        startup-command: "pip install *.whl && python -m uvicorn shipping.app:app --host 0.0.0.0"